### ISSUE TITLE
HardFault when calling SHCI_C2_FLASH_EraseActivity(ERASE_ACTIVITY_OFF)

### ISSUE THREAD

**Issue by JayToltTech** [STMicroelectronics/STM32CubeWB#106]
**Describe the set-up**
 * Custom board based on the WB5M
 * Firmware stm32wb5x_BLE_Stack_full_fw.bin 1.20.0
 * arm-none-eabi-gcc 13.3.1, VSCode, JLink/Ozone, CMake/Ninja

**Describe the bug**
I am refactoring the BLE_OTA sample to work on the WB5M chipset for a custom board.  I am moving the call to Delete_Sectors() from boot initialization time to when the OTAS_STM_WIRELESS_FW_UPLOAD characteristic write is performed so that I can erase different sets of flash pages (starting index and length) depending upon the context from which OTA is called rather than compiling in the starting index and page length to be updated.

I have read through the previous concerns with flash erases during characteristics updates and call:
`aci_l2cap_connection_parameter_update_req(BleApplicationContext.BleApplicationContext_legacy.connectionHandle, 48, 48, 0, 400);`
upon connection establishment to establish a 60 ms connection interval to allow for sufficient flash erase time.  I am using flash_driver.c from the BLE_OTA sample unchanged to perform the necessary SHCI_C2_FLASH steps.

When I execute my code and attempt to erase 0x0B pages at offset 0x0800E000, I can step through the debugger and see FD_EraseSingleSector execute 'properly' 11 times, then when the erasing is complete and the call is made to `SHCI_C2_FLASH_EraseActivity(ERASE_ACTIVITY_OFF);` I get a HardFault with UFSR 0x00010000 or UNDEFINSTR == 1 which seems to imply there is memory corruption occurring.  When I step through the code, it is performing a memcpy in shci_send at the time and I cannot see an issue with the memcpy itself, so I wonder if this is occurring in the M0 core firmware after receiving the shci message that I cannot debug.

Archive attached with .bin and .map, source available upon request to jay at company domain name.

[Archive.zip](https://github.com/user-attachments/files/17196735/Archive.zip)

<img width="970" alt="image" src="https://github.com/user-attachments/assets/1a1cf101-5f44-4aaf-b790-fde917056eaa">

<img width="1108" alt="image" src="https://github.com/user-attachments/assets/0f8f9a96-68f2-4f10-aae1-68321b135696">

**Comment by ALABSTM** [comment]
ST Internal Reference: 192832

**Comment by JayToltTech** [comment]
I reimplemented Delete_Sectors(...) as a FreeRTOS task that is launched from OTAS_STM_Notification -> OTAS_STM_APPLICATION_UPLOAD.  This has the same issue, it succeeds up to the point of when `SHCI_C2_FLASH_EraseActivity(ERASE_ACTIVITY_OFF)` is called which then results in a HardFault.

```
void OTAS_STM_Notification( OTA_STM_Notification_t *p_notification )
...
case OTAS_STM_APPLICATION_UPLOAD:
...
xTaskCreateStatic(&Delete_Sectors_Task, "Delete_Sectors", 256, NULL, configMAX_PRIORITIES - 1U, xStack_Delete_Sectors, &xTask_Delete_Sectors);
...

void Delete_Sectors_Task(void* _) {
  Delete_Sectors(startPage, pagesCount);
  vTaskDelete(NULL);
}

void Delete_Sectors( uint32_t startSector, uint32_t sectorsErasedCount ) {

  TT_LOG_Debug("otas_app", "Delete_Sectors 0x%02x 0x%02x", startSector, sectorsErasedCount);

  uint32_t secureSectorIndex = (READ_BIT(FLASH->SFR, FLASH_SFR_SFSA) >> FLASH_SFR_SFSA_Pos);

  if(startSector < (CFG_APP_START_SECTOR_INDEX - 1))
  {
    CFG_OTA_REBOOT_VAL_MSG = CFG_REBOOT_TO_APP;
    NVIC_SystemReset(); /* it waits until reset */
  }

  if ((startSector + sectorsErasedCount) > secureSectorIndex)
  {
    TT_LOG_Error("otas_app", "Delete_Sectors 0x%02x 0x%02x exceeds secure sector 0x%02x", startSector, sectorsErasedCount, secureSectorIndex);
    Error_Handler();
  }

  while(LL_HSEM_1StepLock(HSEM, CFG_HW_FLASH_SEMID))
    vTaskDelay(1);

  int hr = HAL_FLASH_Unlock();
  if (hr != HAL_OK) {
    Error_Handler();
  }

  hr = SHCI_C2_FLASH_EraseActivity(ERASE_ACTIVITY_ON);
  if (hr != SHCI_Success) {
    Error_Handler();
  }

  for(int flashPage = startSector; (flashPage < startSector + sectorsErasedCount); flashPage++) {

    /* Add at least 5us (CPU1 up to 64MHz) to guarantee that CPU2 can take SEM7 to protect BLE timing */ 
    for (volatile uint32_t i = 0; i < 35; i++);

    FLASH_EraseInitTypeDef p_erase_init;
    p_erase_init.TypeErase = FLASH_TYPEERASE_PAGES;
    p_erase_init.NbPages = 1;
    p_erase_init.Page = flashPage;
    uint32_t page_error;

    while (true) {

      while(LL_FLASH_IsActiveFlag_OperationSuspended()) {
        vTaskDelay(1);
      }

      uint32_t primask_bit = __get_PRIMASK( );
      __disable_irq( );

      // TODO: Never used, not needed?
      //SemStatus_t cpu1_sem_status = (SemStatus_t)LL_HSEM_GetStatus(HSEM, CFG_HW_BLOCK_FLASH_REQ_BY_CPU1_SEMID);
      //if(cpu1_sem_status != SEM_LOCK_SUCCESSFUL) continue;

      SemStatus_t cpu2_sem_status = (SemStatus_t)LL_HSEM_1StepLock(HSEM, CFG_HW_BLOCK_FLASH_REQ_BY_CPU2_SEMID);
      if(cpu2_sem_status != SEM_LOCK_SUCCESSFUL) {
        __set_PRIMASK( primask_bit );
        vTaskDelay(1);
        continue;
      }

      HAL_StatusTypeDef hr = HAL_FLASHEx_Erase(&p_erase_init, &page_error);
      if (hr != HAL_OK) {
        Error_Handler();
      }

      LL_HSEM_ReleaseLock(HSEM, CFG_HW_BLOCK_FLASH_REQ_BY_CPU2_SEMID, 0);
       __set_PRIMASK( primask_bit );

       break;

    }
  }
  
  hr = SHCI_C2_FLASH_EraseActivity(ERASE_ACTIVITY_OFF);
  if (hr != SHCI_Success) {
    Error_Handler();
  }

  hr = HAL_FLASH_Lock();
  if (hr != HAL_OK) {
    Error_Handler();
  }

  LL_HSEM_ReleaseLock(HSEM, CFG_HW_FLASH_SEMID, 0);

}
```

**Comment by ALABSTM** [comment]
Hi @JayToltTech,

Thank you for all these details. Your question has been forwarded to our development teams. Let's wait for their feedback.

With regards,

**Comment by ALABSTM** [comment]
Hi @JayToltTech,

Hope you're fine. Here is the feedback of our development teams after further analysis of your report:

> The customer attempts to erase `0x0B` pages at offset `0x0800E000`. However, according to the `ble-ota.map` file, parts of the BLE-OTA application are located at this offset. As a result, these parts are erased.
Consequently, when the application tries to execute these erased parts, a hard fault is generated.

I hope this analysis helps. Please let me know whether it solves your issue.

With regards,

**Comment by ALABSTM** [comment]
Hi @JayToltTech,

I hope my previous comment provided you with useful information to solve your issue. Please allow me to close this thread. Thank you for your comprehension.

Please do not hesitate to reopen it or post another one in case the issue persists.

With regards,

**Comment by JayToltTech** [comment]
I confirmed that my OTA firmware had grown to exceed the 0x0800E000 size and was overlapping the update flash blocks.  I haven't yet looked into whether moving that boundary fixes the issue, as I had similar crashes on previous builds that didn't exceed the E000 boundary too.

Thanks for the help.

**Comment by ALABSTM** [comment]
Hi @JayToltTech,

Please do not hesitate, should this issue persist and should you have more information to share, to reopen this issue or to log a new one.

With regards,
