### ISSUE TITLE
Missing C++ extern in hci_tl.h

### ISSUE THREAD

**Issue by tim-nordell-nimbelink** [STMicroelectronics/STM32CubeWB#13]
The file Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/tl/hci_tl.h is missing C++ externs.  E.g.:

```
#ifdef __cplusplus
extern "C" {
#endif
```

**Comment by ASELSTM** [comment]
Hi @tim-nordell-nimbelink,

Thank you for this report. You request has been forwarded to our development teams. We will get back to you as soon as they provide us with their feedback.

With regards,

**Comment by ASELSTM** [comment]
Hi @tim-nordell-nimbelink,

The issue has been reported to our development teams and they confirmed it. A fix will be implemented and made available in future release. Thank you once again for your contribution.

With regards,

**Comment by ASELSTM** [comment]
ST Internal Reference: 94219

**Comment by ASELSTM** [comment]
Hi @tim-nordell-nimbelink,

I hope you are fine. The issue you reported has been fixed in the frame of version **v1.10.0** of the STM32CubeWB published recently on GitHub.

Thank you again for having reported.

With regards,
