### ISSUE TITLE
Typo in comments in LL TIM_InputCapture example

### ISSUE THREAD

**Issue by tim-nordell-nimbelink** [STMicroelectronics/STM32CubeWB#16]
Line 145 should read "Enable input channel 1" I believe.

https://github.com/STMicroelectronics/STM32CubeWB/blob/e3d0473c1588f1379ff0e4d7d1c78d081c352518/Projects/P-NUCLEO-WB55.Nucleo/Examples_LL/TIM/TIM_InputCapture_Init/Src/main.c#L142-L146

**Comment by ASELSTM** [comment]
Hi @tim-nordell-nimbelink,

Indeed, there's a typo in the comment, it should be updated as you have mentioned
```diff
- /* Enable output channel 1 */ 
+ /* Enable input channel 1 */ 
```

A fix will be implemented and made available in future release. Thank you once again for your contribution.

With regards,

**Comment by ASELSTM** [comment]
ST Internal Reference: 94247
