### ISSUE TITLE
STM32CubeIDE  Compile error of Mac_802_15_4_FFD 

### ISSUE THREAD

**Issue by ty4tw** [STMicroelectronics/STM32CubeWB#18]
${PARENT-1-PROJECT_LOC}/STM32_WPAN/***app***/app_ffd_mac_802_15_4_process.c
${PARENT-1-PROJECT_LOC}/STM32_WPAN/***app***/app_ffd_mac_802_15_4.c

Change app to ***App*** to avoid compile error.

![Screenshot from 2020-10-10 15-04-33](https://user-images.githubusercontent.com/7830788/95647389-f5b7b280-0b09-11eb-89e8-f53712e15277.png)

**Comment by ASELSTM** [comment]
Hi @ty4tw,

The issue has been confirmed and an bug tracker has been opened internally. A fix will be implemented and made available in the frame of a future release. Thank you once more for your contribution.

With regards,

**Comment by ASELSTM** [comment]
ST Internal Reference: 95353

**Comment by ASELSTM** [comment]
Hi @ty4tw,

I hope you are fine. The issue you reported has been fixed in the frame of version **v1.10.0** of the STM32CubeWB published recently on GitHub.

Thank you again for having reported.

With regards,
