### ISSUE TITLE
BLE_Hid application example missing .ioc file

### ISSUE THREAD

**Issue by Daniel-Khodabakhsh** [STMicroelectronics/STM32CubeWB#20]
## Issue

The `Projects/P-NUCLEO-WB55.Nucleo/Applications/BLE/BLE_Hid` application example appears to be missing an `.ioc` file.
I've tried using `STM32CubeIDE` to create a new project based on this application example and that doesn't generate the `.ioc` file either.

## Question

Is there an `.ioc` file I can borrow from another BLE project which would work with `BLE_Hid`? Or is there a step I'm missing to generate this file?

## Versions

- STM32CubeIDE: `1.4.2`
- STM32CubeWB: `1.9.0`

**Comment by ASELSTM** [comment]
Hi @Daniel-Khodabakhsh,

Thank you for this report. Your question has been forwarded to our development teams. We will get back to you as soon as they provide us with their feedback.

With regards,

**Comment by Daniel-Khodabakhsh** [comment]
Closing, saw the application note AN5155 which states that BLE_Hid is not an MX project.
