### ISSUE TITLE
stm32wb55 firmware hang if add more than 5 services

### ISSUE THREAD

**Issue by 8-DK** [STMicroelectronics/STM32CubeWB#23]
**Describe the set-up**
- Generate code using Stm32cubeMX configure 5 services.
- Added 5 services manually.
- I have added total 10 services and changed the required definitions in header files.

**How To Reproduce**
 * add 10 customer services and 4 characteristics to each service with read-write and notify property.
 * flash firmware.  after flashing firmware tries to connect from the app.
 * firmware will be stuck at
`void hci_cmd_resp_wait(uint32_t timeout)
{
  UTIL_SEQ_WaitEvt(1 << CFG_IDLEEVT_HCI_CMD_EVT_RSP_ID);
  return;
}`

**Additional context**
If you have a first analysis or patch correction, thank you to share your proposal.

**Screenshots**

**Comment by RKOUSTM** [comment]
Hi @8-DK,

TThank you for this report. However, this is rather a Cube MX related issue and I am afraid we do not address it here. Please submit it to the **ST Community**, in the dedicated [section](https://community.st.com/s/topic/0TO0X000000BTr8WAG/stm32cubemx). There you shall find people who will address your request and whom you will hopefully find a solution with.

Please allow me to close this issue now. Thank you for your comprehension.

With regards,
