### ISSUE TITLE
STM32CubeWB/Projects/P-NUCLEO-WB55.Nucleo/Examples/QSPI+READWRITE_IT/

### ISSUE THREAD

**Issue by joseph-amad** [STMicroelectronics/STM32CubeWB#32]
**Describe the set-up**
P-NUCLEO-WB55.Nucleo
N/A

**Describe the bug**
Just wanted to give you guys a heads-up that the pinout for this example is incorrect on the readme file. QSPI3 is hooked up to PA6, not PA8. This means that you must've hooked up PA6 to DQ3, not PA8.

Cheers,
Joseph

**Comment by RKOUSTM** [comment]
Hi @joseph-amad, 

First we would like to thank you for your contribution. An internal tracker has been logged and a fix will be implemented and made available in the frame of a future release.

Thank you once again for your contribution.

With regards,

**Comment by RKOUSTM** [comment]
ST Internal Reference: 110727
