### ISSUE TITLE
Typo in readme "other the air sniffer"

### ISSUE THREAD

**Issue by atsju** [STMicroelectronics/STM32CubeWB#33]
There are at least 3 readme.txt files with this typo in release 1.11.1
> User may use a MAC 802.15.4 other the air sniffer on channel 16 to spy 
>  MAC 802.15.4 broadcasted frames.

I suppose this should be "over the air" instead.

Edit: Additional typo: `reitialize` in code comments instead `reinit...`

**Comment by RKOUSTM** [comment]
Hi @atsju,

Thank you your contribution. Actually, the point you raised has already been dealt and fixed internally. The fix will be made available in the frame of a future release.

Thank you once more for your contribution. 

With regards

**Comment by RKOUSTM** [comment]
ST Internal Reference: 110700
