### ISSUE TITLE
CubeMX database issue STM32WB30

### ISSUE THREAD

**Issue by salkinium** [STMicroelectronics/STM32CubeWB#4]
I've found a data inconsistency in the STM32WB30 mcu file in CubeMX, where the `I2S_CKIN` alternate function is added, but there is no I2S peripheral on the WB30, only the larger devices.

I couldn't find a datasheet or reference manual for this device, it seems to not be released yet, so I cannot check what peripherals the STM32WB30 actually has.

```diff
--- a/mcu/STM32WB30CEUx.xml
+++ b/mcu/STM32WB30CEUx.xml
@@ -74,7 +74,6 @@
  <Pin Name="VDDA" Position="8" Type="Power"/>
  <Pin Name="PA0" Position="9" Type="I/O">
    <Signal Name="ADC1_IN5"/>
-   <Signal Name="I2S_CKIN"/>
    <Signal Name="RTC_TAMP2"/>
    <Signal Name="SYS_WKUP1"/>
    <Signal Name="TIM2_CH1"/>
@@ -145,7 +144,6 @@
    <Signal IOModes="Input,Output,Analog,EVENTOUT,EXTI" Name="GPIO"/>
  </Pin>
  <Pin Name="PB2" Position="19" Type="I/O">
-   <Signal Name="I2S_CKIN"/>
    <Signal Name="LPTIM1_OUT"/>
    <Signal Name="RTC_OUT"/>
    <Signal Name="SPI1_NSS"/>
```

**Comment by ALABSTM** [comment]
Hi @salkinium,

Thank you for this report. As this is related to Cube MX tool, may I ask you to submit it to the ST Community in the dedicated [section](https://community.st.com/s/topic/0TO0X000000BTr8WAG/stm32cubemx)? Indeed, issues shall be related to the software published within this GitHub repository not to ecosystem tools nor any other aspect like hardware or documentation for instance.

Thank you for your comprehension. Take care and stay safe.

With regards,
