### ISSUE TITLE
Init_Exti() does not enable interrupt lines

### ISSUE THREAD

**Issue by maje91** [STMicroelectronics/STM32CubeWB#47]
The function `Init_Exti` found at `Projects/P-NUCLEO-WB55.Nucleo/Applications/BLE/BLE_HeartRate/Core/Src/app_entry.c:163`
is supposed to enable interrupt lines for IPCC and HSEM. The corresponding bits are `&`-ed instead of `|`-ed causing the argument to `LL_EXTI_EnableIT_32_63` to be zero and thus no interrupt lines are enabled. `grep`ing for this shows that the error is present in many of the example applications.

**Comment by ALABSTM** [comment]
Hi @maje91,

Thank you for this report. We will get back to you with a feedback as soon as possible. Please excuse the delay it may take us sometimes to reply. Thank you for your comprehension.

With regards,

**Comment by RKOUSTM** [comment]
Hi @maje91,

 First of all we would like to thank you for your report. 

An internal tracker has been logged and a fix will be published in the frame of a future release.

Thank you again for your report.

With regards,

**Comment by RKOUSTM** [comment]
ST Internal Reference: 123480

**Comment by ASELSTM** [comment]
Hi @maje91,

Thank you for your contribution. This issue has been fixed in the frame of version v1.14.0 of the STM32CubeWB published recently. Please allow me then to close this thread.

Thank you again for your contribution.

With regards,
