### ISSUE TITLE
IEEE 802.15.4 Security

### ISSUE THREAD

**Issue by medaliyou** [STMicroelectronics/STM32CubeWB#49]
**Describe the set-up**
 * The board : STM32WB55 NUCLEO
 * STM32CubeIDE latest (1.7.0).

**Additional context**
The ST WPAN Middleware for IEEE 802.15.4 doesn't provide an implementation for the relevant Security PIB attributes and procedures nor its documentation.

**Comment by ASELSTM** [comment]
ST Internal Reference: 121722

**Comment by ASELSTM** [comment]
Hi @medaliyou,

Thank you for your contribution. Unfortunately, the security features are not supported on MAC-802.15.4. We also do not support them on STM32CubeWB package. 

Hope this would help you. Please allow me thus to close this thread. Thank you for your comprehension.

With regards,
