### ISSUE TITLE
P-NUCLEO-WB55.Nucleo BLE_TransparentMode bug in UART initialization when porting to a user board using LPUART1 instead of USART1.

### ISSUE THREAD

**Issue by Xevel** [STMicroelectronics/STM32CubeWB#55]
Hello,

In STM32Cube_FW_WB_V1.13.1/Projects/P-NUCLEO-WB55.Nucleo/Applications/BLE/BLE_TransparentMode/STM32_WPAN/App/tm.c

line 170, there is a call to 
`MX_USART1_UART_Init();`

It should be dependent upon definition of CFG_HW_LPUART1_ENABLED or CFG_HW_USART1_ENABLED, to either init USART1 or LPUART1.

Best regards,
Xevel

**Comment by ASELSTM** [comment]
Hi @Xevel,

Thank you for your contribution. This issue has been fixed in the frame of version v1.15.0 of the STM32CubeWB. Please allow me then to close this thread.

With regards,
