### ISSUE TITLE
HCI_LE_TEST_END long response (BLE_TransparentMode - STM32WB55)

### ISSUE THREAD

**Issue by sebachm94** [STMicroelectronics/STM32CubeWB#64]
Hi, I'm trying to run BLE_TransparentMode on my STM32WB55VG for DTM purposes. I'm using FUS 1.2.0, Wireless Stack 1.13.2 (stm32wb5x_BLE_HCILayer_extended_fw), BLE_TransparentMode app 1.13.2. 
I'm building it in STM32CubeIde 1.8.0 with CubeMX 6.4.0, only thing I'm changing comparing to default config is USART-TX pin from PB7 to PA9 (in .ioc file).
App works almost fine. It responds for most of the commands but there is a problem while performing TX test. 
HCI_LE_TRANSMITTER_TEST is sent and I got Command Complete as a result, then I'm trying to send HCI_LE_TEST_END and here is the problem. Response goes back after ~30sec, with Command Complete as result. The same app works fine for my Nucleo Board with STM32WB55 (with the same stack and FUS).

Can you help me figure it out what I could do wrong or where to debug?

BR,
Sebastian

**Comment by ASELSTM** [comment]
Hi @sebachm94,

> only thing I'm changing comparing to default config is USART-TX pin from PB7 to PA9 (in .ioc file).

Note that PB7 is actually a **_USART1_RX_** pin while PA9 is a **_USART1_TX_** pin. Would please check the pins you have changed. 

With regards,
