### ISSUE TITLE
HAL Flash missing support for STM32WB10xx

### ISSUE THREAD

**Issue by nicreuss** [STMicroelectronics/STM32CubeWB#70]
**Set-up**
- STM32CubeIDE v1.10.0
- Custom PCB with STM32WB10CC

**Problem**
The STM32WB10CC chip has a flash page size of 2 kByte ([RM0478 Rev 5 pg 61](https://www.st.com/resource/en/reference_manual/rm0478-multiprotocol-wireless-32bit-mcu-armbased-cortexm4-with-fpu-bluetooth-52-radio-solution-stmicroelectronics.pdf))
The `stm32wbxx_hal_flash.h` header [defines the flash page size as 4 kByte](https://github.com/STMicroelectronics/STM32CubeWB/blob/c5e996bd6754f34989d271ce18902b281bed8bcb/Drivers/STM32WBxx_HAL_Driver/Inc/stm32wbxx_hal_flash.h#L858)

**Solution**
There are other features in the HAL (like RCC and TIM) that explicitly support the STM32WB10xx device series. It appears that the HAL flash feature needs to be updated to support the STM32WB10xx series.

For example, in the case of flash page size, [this code](https://github.com/STMicroelectronics/STM32CubeWB/blob/c5e996bd6754f34989d271ce18902b281bed8bcb/Drivers/STM32WBxx_HAL_Driver/Inc/stm32wbxx_hal_flash.h#L858) would become:
```c
#if defined(STM32WB10xx) || defined(STM32WB15xx) || defined(STM32WB1Mxx)
#define FLASH_PAGE_SIZE                         0x00000800U  /*!< FLASH Page Size, 2 KBytes */
#else
#define FLASH_PAGE_SIZE                         0x00001000U  /*!< FLASH Page Size, 4 KBytes */
#endif
```

**Comment by TOUNSTM** [comment]
Hello,

Thank you for your contribution, I have noticed that this issue has also been raised [here](https://github.com/STMicroelectronics/STM32CubeWB/pull/62). Please allow me to mark this one as a duplicate and to close it 

Best Regards,
