### ISSUE TITLE
Feature Request: Allow Device Information Service generation without requiring another ST defined BLE service

### ISSUE THREAD

**Issue by Bradley-Cooley** [STMicroelectronics/STM32CubeWB#72]
Currently it seems the device information service implementation provided by ST through CubeMX code generation is hidden behind usage of other services. I am not creating a, for example, Heart Rate device, but I do want to use the DIS service. I unfortunately cannot use STs DIS service through CubeMX because there is no option to generate it outside the context of other services, and the autogeneration step will delete the DIS files if I remove the i.e. Heart Rate service.

It would be nice if I could use the DIS service standalone.

**Comment by RJMSTM** [comment]
ST Internal Reference: 159311

**Comment by RJMSTM** [comment]
Hello @Bradley-Cooley,

If I well understand the User try to create a WB55 BLE application that advertise one service the Device Information by deleting in the WB55 BLE Heart Rate application the Heart Rate service.

The best way to create a WB55 BLE application with CubeMx is to create the application from scratch.
There is a wiki page that can help to create a custom WB55 BLE application from scratch with CubeMx at the following address:
https://wiki.st.com/stm32mcu/wiki/Connectivity:STM32WB_BLE_STM32CubeMX

Let me know if with this wiki page you can create his custom WB55 BLE application.
