### ISSUE TITLE
Thread_RCP for P-NUCLEO-WB55 USB Dongle ?

### ISSUE THREAD

**Issue by joelguittet** [STMicroelectronics/STM32CubeWB#76]
Hello

Is there any plan to have the Thread_RCP application on the P-NUCLEO-WB55 USB Dongle ?

Actually it is available for the P-NUCLEO-WB55 dev board and using an FTDI adapter. I would be amazing to have the dongle as well, with virtual serial port instead of the FTDI cable!

Thanks for the update,
Joel

**Comment by HBOSTM** [comment]
Hello @joelguittet,

Unfortunately, there is no plan in the near future to create the Thread_RCP application on the P-NUCLEO-WB55 USB Dongle. We will keep you informed, should there be any update in this plan.
Please allow me to close this issue. Thank you for your comprehension and thank you for your report.

Best Regards,
