### ISSUE TITLE
Custom_STM_App_Update_Char() could include a size parameter for supporting characteristics with variable length 

### ISSUE THREAD

**Issue by marcelobarrosufu** [STMicroelectronics/STM32CubeWB#85]
In CubeIDE we may define characteristics with variable length (Length characteristic as variable and value length with maximum size). 

However, when the code is generated (Custom P2P Server disabled and Custom Template is enabled in BLE Applications and services) [the generated code ](https://github.com/STMicroelectronics/STM32CubeWB/blob/7564de628d7e4ec78bd5442d288697a8604d6f31/Middlewares/ST/STM32_WPAN/ble/svc/Src/template_stm.c#L260C19-L260C19) for updating characteristic values do not have any length parameter. 

The default size is controlled by local variables inside custom_stm.c and we do have access to the CustomContext as well since it is static inside custom_stm.c. So, we can´t change the size from external code.

The default implementation for Custom_STM_App_Update_Char is below:

`
tBleStatus Custom_STM_App_Update_Char(Custom_STM_Char_Opcode_t CharOpcode, uint8_t *pPayload)
{
 // ...
}
`

This way, we need to reimplement Custom_STM_App_Update_Char inside custom_stm.c, probably using some protection area. How about to add a support for size in this function call ? Something like:

`
tBleStatus Custom_STM_App_Update_Char(Custom_STM_Char_Opcode_t CharOpcode, uint8_t *pPayload, uint16 size)
{
 // ...
}
`

Thanks a lot !

![image](https://github.com/STMicroelectronics/STM32CubeWB/assets/36000163/81104b3a-7b2b-4f34-8f00-baa2ed2d9183)

![image](https://github.com/STMicroelectronics/STM32CubeWB/assets/36000163/ae914d57-0bfd-4edc-b586-767283e222fe)

**Comment by RJMSTM** [comment]
ST Internal Reference: 169675

**Comment by RJMSTM** [comment]
Hello,

I hope you are fine. The issue you reported has been fixed in the frame of version v1.20.0 of the STM32CubeWB published recently on GitHub. Thank you again for having reported.
