### ISSUE TITLE
ble_gatt_aci.h missing C++ support

### ISSUE THREAD

**Issue by raitraak-rrk** [STMicroelectronics/STM32CubeWB#95]
Middlewares/ST/STM32_WPAN/ble/core/auto/ble_hal_aci.h is missing C++ support. Many other STM32_WPAN files look the same.

#ifdef __cplusplus
extern "C" {
#endif

**Comment by RJMSTM** [comment]
ST Internal Reference: 186693

**Comment by RJMSTM** [comment]
Hello,

Thank you for your contribution. You need to include "Middlewares\ST\STM32_WPAN\ble\ble.h" before BLE_ACI.h.

Regards,

**Comment by raitraak-rrk** [comment]
Thanks. However, this seems more of a undocumented workaround rather than a fix.

**Comment by RJMSTM** [comment]
Hello,

A cleaner solution is to select the STM32_WPAN group in Middlewares and go in "Options" panel, "C/C++ Compiler" and select "Override inherited settings" and select C language.

Regards,

**Comment by raitraak-rrk** [comment]
There is no "Options" panel when using git repo directly.
