### ISSUE TITLE
aci_gap_start_connection_update return 0x12

### ISSUE THREAD

**Issue by huangliguang** [STMicroelectronics/STM32CubeWB#96]
ble version：v1.20.0
`                result = aci_gap_create_connection(SCAN_P,
                                                   SCAN_L,
                                                   server_Remote_Addr[i].adv_t.SERVER_REMOTE_ADDR_TYPE, server_Remote_Addr[i].adv_t.SERVER_REMOTE_BDADDR,
                                                   CFG_BLE_ADDRESS_TYPE,
                                                   CONN_P(82),
                                                   CONN_P(82),
                                                   0,
                                                   SUPERV_TIMEOUT,
                                                   CONN_L(8),
                                                   CONN_L(8));`

conn success then call aci_gap_start_connection_update 
`result = aci_gap_start_connection_update(server_Remote_Addr[i].BleApplicationContext_legacy.connectionHandle,
                         CONN_P(82),
                         CONN_P(82),
                         10, 
                         150,
                         CONN_L(8), CONN_L(8));`

but retrun 0x12

test is  1 master and 1 slave

**Comment by ALABSTM** [comment]
Hi @huangliguang,

Would you mind providing more details about this issue. A template is provided to guide you. This would help us supporting you.

With regards,

**Comment by ALABSTM** [comment]
Hi @huangliguang,

Please allow me to close this thread as no feedback so far. Thank you for your comprehension.

With regards,
