### ISSUE TITLE
aci_gatt_disc_all_primary_services sometime return 0xc

### ISSUE THREAD

**Issue by huangliguang** [STMicroelectronics/STM32CubeWB#97]
You must power it on again to return 0x00

**Comment by ALABSTM** [comment]
Hi @huangliguang,

Would you mind providing more details about this issue please? We provide a template with different sections to fill with the relevant information. Thank you for your comprehension.

With regards,

**Comment by ALABSTM** [comment]
Hi @huangliguang,

Please allow me to close this issue as the information provided is not easily understandable and usable. Thank you for your comprehension.

With regards,
